/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.home;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class AppTest {
    @Test public void testSomeLibraryMethod() {
        App classUnderTest = new App();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
